# =========================================================
# BaseConfig
# =========================================================
data_dir: "./dataset/SnapBench-hard-clean/dev"
level: "hard"
results_dir: "./results0315"
sql_execution_timeout: 15
concurrency: 8
skip_visual_api_call: True

# =========================================================
# OSS
# =========================================================
use_oss: true
oss_access_key_id: ""
oss_access_key_secret: ""
oss_endpoint: ""
oss_bucket_name: ""
oss_dir_prefix: ""

# =========================================================
# PipelineConfig - Visual
# =========================================================
visual_model: "qwen3-vl-plus"
# visual_model: "gpt-5.2"

visual_model_base_url: ""
visual_model_api_key: ""

max_width: 2048
max_height: 4096
overlap: 200

# =========================================================
# Generation Parameters
# =========================================================
temperature: 0.0
top_p: 0.1
frequency_penalty: 0.0
presence_penalty: 0.0
max_tokens: 16384
seed: 42

# =========================================================
# PipelineConfig - Text2SQL
# =========================================================
text2sql_model_base_url: ""
text2sql_model_api_key: ""
text2sql_model: "MAC-SQL"